/**
 * Migrated from first-draft EMOTA (`nextjs-emota-v1/data/trivia.ts`).
 * A few entries were reworded for accuracy; indices `a` are before shuffle (see trivia.ts).
 */
export interface TriviaDraftRaw {
  readonly id: string;
  readonly q: string;
  readonly o: readonly [string, string, string, string];
  /** Correct index before shuffle */
  readonly a: 0 | 1 | 2 | 3;
  readonly cat: string;
}

export const TRIVIA_DRAFT_RAW: readonly TriviaDraftRaw[] = [
  {
    id: "v1_1",
    q: "In what year did Ezra Meeker first travel the Oregon Trail?",
    o: ["1852", "1860", "1848", "1856"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_2",
    q: "What was Ezra Meeker's primary business in Puyallup Valley?",
    o: ["Hop farming", "Cattle ranching", "Gold mining", "Lumber milling"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_meeker_1906",
    q: "Why did Ezra Meeker retrace the Oregon Trail in 1906?",
    o: [
      "To preserve its history and mark the trail",
      "To find gold",
      "To establish new settlements",
      "To map a new route",
    ],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_4",
    q: "What mode of transportation did Meeker use in his 1916 trail journey?",
    o: ["Automobile", "Horse and wagon", "Train", "Bicycle"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_5",
    q: "Roughly what share of U.S. hop production came from Washington State in recent years?",
    o: ["A large majority (roughly three-quarters or more)", "Around half", "Less than a quarter", "About one-third"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_6",
    q: "Which Yakima-area hop variety is famous for citrus and pine aroma in brewing?",
    o: ["Cascade", "Saaz", "Hallertau", "Fuggle"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_7",
    q: "What was a realistic daily water requirement for one ox on a hot trail day?",
    o: ["Roughly 8–10 gallons", "2–3 gallons", "15–20 gallons", "Under 1 gallon"],
    a: 0,
    cat: "survival",
  },
  {
    id: "v1_common_disease",
    q: "Which disease terrorized wagon companies and river towns in many trail-era accounts?",
    o: ["Cholera", "Smallpox", "Influenza", "Measles"],
    a: 0,
    cat: "health",
  },
  {
    id: "v1_9",
    q: "Which Wyoming landmark did emigrants use as a calendar goal — “reach it by the Fourth”?",
    o: ["Independence Rock", "Devil's Gate", "Chimney Rock", "Scott's Bluff"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_10",
    q: "What made the Yakima Valley workable for irrigated hop fields?",
    o: ["Dry summers with controlled irrigation", "Year-round monsoon rain", "Tropical heat", "Pure sand dunes"],
    a: 0,
    cat: "nature",
  },
  {
    id: "v1_11",
    q: "Ezra Meeker’s trail-marking crusade included early monuments close to his home base in:",
    o: ["The Puyallup area", "Boston Harbor", "New Orleans levees", "Charleston forts"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_12",
    q: "Hop lice (aphids) helped bust the Northwest hop boom in which year often cited for Meeker?",
    o: ["1891", "1885", "1889", "1893"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_13",
    q: "In the 1880s, Puyallup Valley hops often sailed to buyers in:",
    o: ["England", "Germany", "Belgium", "Netherlands"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_14",
    q: "Modern brewers and hop suppliers sometimes partner on “heritage” blends — the idea is to:",
    o: [
      "Spotlight Northwest hop history tied to pioneers like Meeker",
      "End all craft brewing",
      "Replace hops with artificial flavor",
      "Ban Yakima exports",
    ],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_15",
    q: "What stunt made headlines on Meeker’s 1920s trail tours?",
    o: [
      "Flying part of the route by airplane in his nineties",
      "Walking every mile barefoot",
      "Only traveling by submarine",
      "Refusing to speak in public",
    ],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_16",
    q: "Washington’s Yakima Valley remains a global powerhouse in hop acreage — that means:",
    o: [
      "A very large share of world supply still comes from there",
      "Hops no longer grow there",
      "Only one farm remains",
      "All hops are imported to Yakima",
    ],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_17",
    q: "Which hop, bred from USDA work in the Pacific Northwest, helped define American pale ale aroma?",
    o: ["Cascade", "Centennial", "Chinook", "Columbus"],
    a: 0,
    cat: "nature",
  },
  {
    id: "v1_18",
    q: "Washington hop exports today are best described as:",
    o: [
      "A major state export industry (order of hundreds of millions of dollars)",
      "Negligible trade value",
      "Illegal to ship",
      "Only sold in coin rolls",
    ],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_19",
    q: "In his old age, Meeker lobbied hardest for governments to:",
    o: [
      "Mark the Oregon Trail and build usable motor roads for memory tourism",
      "Abolish all railroads",
      "Sell the trail to private mines",
      "Stop all westbound mail",
    ],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_20",
    q: "The Whitman Mission site near Walla Walla — part of the same migration story Meeker remembered — is:",
    o: [
      "A National Historic Landmark (among other federal protections)",
      "Only a shopping mall",
      "Unmarked sagebrush with no signage",
      "A naval submarine base",
    ],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_21",
    q: "Meeker’s Puyallup hop operations sat on homelands long stewarded by:",
    o: ["The Puyallup Tribal people", "The Navajo Nation", "The Seminole Tribe", "The Penobscot Nation"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_22",
    q: "Proprietary aroma hops like Citra® are overwhelmingly grown where?",
    o: ["Pacific Northwest hop yards (especially Yakima-area supply)", "Sahara farms", "Undersea nets", "Antarctic greenhouses"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_23",
    q: "Japanese brewers began buying Yakima hops directly in the 1960s — one early name often cited is:",
    o: ["Kirin", "Asahi", "Sapporo", "Suntory"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_24",
    q: "Northwest hop picking mechanized over the 20th century — that mainly meant:",
    o: [
      "Combines and stationary pickers replacing huge hand crews",
      "Oxen only, forever",
      "Banning all exports",
      "Deleting irrigation",
    ],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_25",
    q: "The Cascade hop variety was released to growers in which decade?",
    o: ["1970s", "1920s", "1990s", "1950s"],
    a: 0,
    cat: "nature",
  },
  {
    id: "v1_26",
    q: "A mature hop bine in peak summer is thirsty — growers think in terms of:",
    o: ["Several gallons per day per plant through drip or irrigation", "A cup of water per season", "Only fog", "No water ever"],
    a: 0,
    cat: "nature",
  },
  {
    id: "v1_27",
    q: "Sustainable hop farms today echo older mixed farming by:",
    o: [
      "Rotating ground crops and soil care, not mining the same field forever",
      "Paving every acre",
      "Ignoring pests",
      "Skipping all fertilizer planning",
    ],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_28",
    q: "Germany and Japan are still major buyers of Washington hops because:",
    o: [
      "Their large breweries need reliable aroma and bittering supply",
      "Hops are illegal there",
      "Washington does not export",
      "Only tea is brewed in Europe",
    ],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_29",
    q: "Yakima Valley hop farms are still often:",
    o: ["Family operations and grower networks with deep local roots", "Owned only by Martian robots", "Banned since 1890", "Single corporation worldwide"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_30",
    q: "Why do brewers still name-check Ezra Meeker in hop country marketing?",
    o: [
      "He linked Puyallup/Yakima hops to national markets and trail memory",
      "He invented aluminum cans",
      "He opposed all beer",
      "He only sold maple syrup",
    ],
    a: 0,
    cat: "nature",
  },
  {
    id: "v1_start_point",
    q: "What was the main jumping-off town name on the classic Oregon Trail?",
    o: ["Independence, Missouri", "St. Louis, Missouri", "Chicago, Illinois", "Detroit, Michigan"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_trail_length",
    q: "Approximately how long was the Oregon Trail?",
    o: ["About 2,000 miles", "About 1,000 miles", "About 3,000 miles", "About 500 miles"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_travel_time",
    q: "How long did it typically take to travel the Oregon Trail?",
    o: ["About 4–6 months", "1–2 months", "About a full year", "About two weeks"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_wagon_name",
    q: "What was the nickname for the common canvas-topped wagons on the trail?",
    o: ["Prairie schooners", "Desert ships", "Trail runners", "Mountain movers"],
    a: 0,
    cat: "transportation",
  },
  {
    id: "v1_river_crossing",
    q: "Which river leg was notorious for raft crossings, steep banks, and emigrant panic?",
    o: ["Snake River", "Missouri River", "Columbia River", "Platte River"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_plains_peoples",
    q: "Along the Platte and Sweetwater, diaries often mention uneasy contact with:",
    o: [
      "Northern Plains nations such as Lakota kin, Cheyenne, and Arapaho",
      "Cherokee removal parties only",
      "Navajo herders",
      "Apache bands from the desert Southwest",
    ],
    a: 0,
    cat: "culture",
  },
  {
    id: "v1_peak_year",
    q: "Which year is often called the peak “flood” year of Oregon Trail travel?",
    o: ["1852", "1842", "1862", "1872"],
    a: 0,
    cat: "history",
  },
  {
    id: "v1_supplies_cost",
    q: "Outfitting a family for the trail could easily run:",
    o: ["Hundreds of dollars in 1850s money — a serious stake", "$10 total", "Nothing — the army paid everyone", "Millions in gold only"],
    a: 0,
    cat: "economics",
  },
  {
    id: "v1_wagon_weight",
    q: "Practical guides warned against loading a wagon beyond roughly:",
    o: ["About 2,000 pounds including people", "10,000 pounds", "500 pounds always", "No limit"],
    a: 0,
    cat: "transportation",
  },
  {
    id: "v1_best_month",
    q: "Most companies tried to leave Missouri in:",
    o: ["April–May grass window", "Deep January ice", "Late August heat", "November mud"],
    a: 0,
    cat: "planning",
  },
  {
    id: "v1_trail_end",
    q: "The measured trail’s common terminus for land claims was:",
    o: ["Oregon City", "Portland", "Salem", "Eugene"],
    a: 0,
    cat: "geography",
  },
  {
    id: "v1_food_supply",
    q: "Bulk calories on the trail usually meant sacks of:",
    o: ["Flour", "Ice cream", "Fresh salad", "Sushi"],
    a: 0,
    cat: "supplies",
  },
  {
    id: "v1_landmarks",
    q: "Which landmark was the famous “reach it by Independence Day” milestone?",
    o: ["Chimney Rock", "Fort Laramie", "Independence Rock", "South Pass"],
    a: 2,
    cat: "geography",
  },
];
